{
 "title": "Torque",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Filename",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(bucket: \"torque\", tag: \"filename\", start: v.timeRangeStart, stop: v.timeRangeStop)\r\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Trip Distance",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"torque\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"torque\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Trip Distance(km)\")\r\n  |> filter(fn: (r) => r[\"filename\"] == \"${Filename}\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Fuel Used",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"torque\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"torque\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Fuel used (trip)(l)\")\r\n  |> filter(fn: (r) => r[\"filename\"] == \"${Filename}\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Average fuel efficieny",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "km/l" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"torque\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"torque\")\r\n  |> filter(fn: (r) => r[\"filename\"] == \"${Filename}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Trip average KPL(kpl)\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Trip Cost",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyINR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"torque\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"torque\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Fuel used (trip)(l)\")\r\n  |> filter(fn: (r) => r[\"filename\"] == \"${Filename}\")\r\n  |> map(fn: (r) => ({ r with fuel_cost: r._value * 108.0}))\r\n  |> keep(columns: [\"fuel_cost\"])\r\n  |> rename(columns: {\"fuel_cost\": \"_value\"})\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Trip",
   "type": "geomap",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"torque\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"torque\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Latitude\" or r[\"_field\"] == \"Longitude\" or r[\"_field\"] == \"Kilometers Per Litre(Instant)(kpl)\")\r\n  |> filter(fn: (r) => r[\"filename\"] == \"${Filename}\")\r\n  |> aggregateWindow(every: 10s, fn: last, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group()\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_time\",\"_measurement\"])"
    }
   ]
  }
 ]
}